import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Link href="/" className="banner_in">
          <header>
            해람.in
          </header>
        </Link>
        <nav>
          <div className="left-menu">
            <Link href="/list">정보 살펴보기</Link>
          </div>
          <div className="right-menu">
            <Link href="/post/new">글 발행</Link>
            <Link href="/login">로그인</Link>
            <Link href="/signup">회원 가입</Link>
          </div>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          <p>Made by Tiger`jy teem</p>
          <p className="contact-info">
            Contact: wonyoungjang(teamleader) <a href="mailto:zwonyoung@gwnu.ac.kr">zwonyoung@gwnu.ac.kr</a>
          </p>
          <p>
            Project Repository: <a href="https://github.com/hexter31376/heram_in" target="_blank" rel="noopener noreferrer">View on GitHub</a>
          </p>
        </footer>
      </body>
    </html>
  );
}
